---
driver:
  name: vagrant
  require_chef_omnibus: 12.4.3
  synced_folders:
    - [".", "/vagrant"]

provisioner:
  name: chef_zero
  environments_path: test/environments
  client_rb:
    no_proxy: localhost,127.0.0.1
    environment: default

platforms:
  - name: ubuntu-14.04

suites:
  - name: kibana
    run_list:
      - recipe[mycookbook::kibana]
